# Generated by Django 3.1.2 on 2021-11-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pull_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_request_id', models.IntegerField()),
                ('number', models.IntegerField()),
                ('url', models.URLField()),
                ('state', models.CharField(max_length=100)),
                ('locked', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField()),
                ('body', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('merged_at', models.DateTimeField()),
            ],
        ),
    ]
